### PR TITLE
Update HtmlReplacer.php

### PR DESCRIPTION
**Pull request by wilfriedwolf**
Avoids attributes from different tags

### CODE REVIEW

**Comment by wilfriedwolf** [comment]
Solves issue introduced by https://github.com/yireo/Yireo_NextGenImages/pull/83

**Comment by hostep** [comment]
I think you will also need to update the regex in `unmaskAngleBracketsInsideQuotes`, as it will also match things you don't want to change: https://regex101.com/r/KsPdmb/1

In my opinion, this regex solution is a wrong approach to fix https://github.com/yireo/Yireo_NextGenImages/issues/82, it just will cause too many edge case issues as it works on the entire html output of a page. Can't we limit it to only operate on image/picture tags? So that it only applies to html output inside that `foreach ($images as $image) {` section?

**Comment by jissereitsma** [comment]
I've now added an alternative fix, simply by adding a more complex regex in the right place: https://github.com/yireo/Yireo_NextGenImages/commit/867ef31da8920f1cc581bd6194f1068e7ab6bdda#diff-56e9cb219161815f1d7336e26a686ab654e4ce468c6cf20463274e162a7b4ffdR116

**Comment by hostep** [comment]
Thanks Jisse!

**Comment by wilfriedwolf** [comment]
Thanks from me too, sorry for the inconveniences caused.

**Comment by jissereitsma** [comment]
No worries, I'm happy that we could work together to improve things!

**Pull request closed without merging**
